### PR TITLE
Add new scaling function SCALE_LIM.fct with limit feature. Define input/output variables and logic for scaling calculation.

### PR DESCRIPTION
**Pull request by franz-hoepfinger-4diac**
Add new scaling function SCALE_LIM.fct with limit feature. Define input/output variables and logic for scaling calculation.

### CODE REVIEW

**Review by azoitl — COMMENTED** [review]
I find excape a strange name for the upper and lower bounds. Normally I would call them limit. Also the four different escape values can not be understood just from the names.

**Comment by franz-hoepfinger-4diac** [comment]
> I find excape a strange name for the upper and lower bounds. Normally I would call them limit. Also the four different escape values can not be understood just from the names.

you are right, i will propose better names.

**Comment by franz-hoepfinger-4diac** [comment]
@azoitl see now. 
i also changed SCALE, to be consistent. 
see https://github.com/eclipse-4diac/4diac-ide/pull/527

**Comment by franz-hoepfinger-4diac** [comment]
image

**Review by azoitl — APPROVED** [review]

**Pull request merged**
