### PR TITLE
VarInOuts where missing in execution event function call

### PR DESCRIPTION
**Pull request by azoitl**
For the generated FB Body for a function the call to the function didn't pass varinout variables.

### CODE REVIEW

**Review by mx990 — CHANGES_REQUESTED** [review]
I belive the `inOutVars` are also missing in the constructor initializer list on line 46 and the `setInitialValues` definition on line 51.

**Comment by azoitl** [comment]
> I belive the `inOutVars` are also missing in the constructor initializer list on line 46 and the `setInitialValues` definition on line 51.

For Basic and Simple FBs they are also not there. Should they be there in all places or in none?

**Comment by mx990** [comment]
> > I belive the `inOutVars` are also missing in the constructor initializer list on line 46 and the `setInitialValues` definition on line 51.
> 
> For Basic and Simple FBs they are also not there. Should they be there in all places or in none?

They should be there in all places (i.e., `BaseFBImplTemplate`, `CompositeFBImplTemplate`, and `ServiceInterfaceFBImplTemplate`).

**Comment by azoitl** [comment]
> > > I belive the `inOutVars` are also missing in the constructor initializer list on line 46 and the `setInitialValues` definition on line 51.
> > 
> > 
> > For Basic and Simple FBs they are also not there. Should they be there in all places or in none?
> 
> They should be there in all places (i.e., `BaseFBImplTemplate`, `CompositeFBImplTemplate`, and `ServiceInterfaceFBImplTemplate`).

done

**Review by mx990 — APPROVED** [review]

**Pull request merged**
