### PR TITLE
Add INI File Storage FB

### PR DESCRIPTION
**Pull request by franz-hoepfinger-4diac**
Add INI File Storage FB

### CODE REVIEW

**Review by azoitl — COMMENTED** [review]
why not just one block with any in and outputs for the values? It is anyhow an sifb.

**Comment by diplfranzhoepfinger** [comment]
> why not just one block with any in and outputs for the values? It is anyhow an sifb.

this is the reason i am posting it that way. 

YES, makes Sense. I change it.

**Comment by diplfranzhoepfinger** [comment]
chnaged to ANY

**Comment by diplfranzhoepfinger** [comment]
better with ANY\_ELEMENTARY  
[https://www.fernhillsoftware.com/help/iec-61131/common-elements/datatypes-generic.html](https://www.fernhillsoftware.com/help/iec-61131/common-elements/datatypes-generic.html)

Struct and Array Types might be difficult,  
while INT, Real and STRING is possible.

**Review by azoitl — APPROVED** [review]

**Pull request merged**
