### PR TITLE
Added Test Suit for DataType Editor

### LINKED ISSUE #153: UI testing for Type Editor using SWT
It's noted that on IDE, timely UI seems broken which results in poor user experience and frequent errors. To overcome these issues, there is a strong need for an automated test suite for the graphical editors part. These test suites will detect errors that will enhance the overall reliability of the editors. Through automated testing, we can effectively implement error indicators within graphical models, ensuring timely identification and resolution of issues.

This can be achieved by creating UI automated test suites which we are doing using SWTBot. With this issue, we are focusing mainly on type editors. 
The whole UI testing for type editors has been divided into modules as below:

- [x] CreateFBTModule
- [x] BasicFBTOperationModule
- [x] ECCModule
- [ ] ExportFBTModule 
- [x] DataTypeEditorModule
- [x] InteractionTabModule

### PR DESCRIPTION
**Pull request by ShantKhatri**
part of #153 

Test suites for Data Type Editor, these changes test the different scenarios of the data type table. 
Scenarios Include:

- Rename variable
- Change variable name with button
- Change name of variable with existing name
- Set invalid name
- Reorder variable
- Change datatype of variable
- Set invalid datatype
- Change comment of the variable
- Change initial value of the variable
- Set invalid initial value

### CODE REVIEW

**Comment by bwiesmayr** [comment]
@ShantKhatri I'm afraid there were some compile errors in the PR. Can you check that

**Comment by ShantKhatri** [comment]
> @ShantKhatri I'm afraid there were some compile errors in the PR. Can you check that

It has a dependency on #344, once that gets merged then we have to update this PR.

**Comment by bwiesmayr** [comment]
> > @ShantKhatri I'm afraid there were some compile errors in the PR. Can you check that
> 
> It has a dependency on #344, once that gets merged then we have to update this PR.

I see, just merged #344

**Comment by ShantKhatri** [comment]
> > > @ShantKhatri I'm afraid there were some compile errors in the PR. Can you check that
> > 
> > 
> > It has a dependency on #344, once that gets merged then we have to update this PR.
> 
> I see, just merged #344

Thanks! I'm updating this one.

**Review by bwiesmayr — APPROVED** [review]

**Review by azoitl — APPROVED** [review]

**Pull request merged**
