### PR TITLE
Add new FBType RangeBasedPulse for Distance based Impulse Generator.

### PR DESCRIPTION
**Pull request by franz-hoepfinger-4diac**
Add new FBType RangeBasedPulse for Distance based Impulse Generator.

Typical usage: 

this would e.g. paint the middle dash-line on a Street: 
5000 Line, with 5000 Gap. 

image

### CODE REVIEW

**Comment by franz-hoepfinger-4diac** [comment]
Make Sense to add a Distance Offset! 

image

**Review by azoitl — CHANGES_REQUESTED** [review]
Please don't use the GEN_ prefix for such blocks. The GEN_ prefix is used in Eclipse 4diac for configurable types (e.g., publish). Also distance is maybe not the best name as I could feed it any value to generate pulses. 

Would `RangeBasedPulse` be better?

**Comment by diplfranzhoepfinger** [comment]
> Please don't use the GEN\_ prefix for such blocks. The GEN\_ prefix is used in Eclipse 4diac for configurable types (e.g., publish).

sorry, yes, normally i know this. 

>  Also distance is maybe not the best name as I could feed it any value to generate pulses.

you are right. it might be Time, it might be Distance, or it might be any Value from any Source. 

e.g. generate Pulses dependent of a Sensor Value. 

> Would `RangeBasedPulse` be better?

yes, will change

**Comment by franz-hoepfinger-4diac** [comment]
@azoitl changed

**Review by azoitl — APPROVED** [review]

**Comment by franz-hoepfinger-4diac** [comment]
https://github.com/eclipse-4diac/4diac-ide/pull/760

**Pull request merged**
