### PR TITLE
autolayout imrovements for expanded subapps

### PR DESCRIPTION
**Pull request by lindhuber**
Contains some changes to improve code and layout quality as well as the possibility to layout expanded subapps by selecting everything(ctrl+a) and calling the new menu entry.

### CODE REVIEW

**Comment by oberlehner** [comment]
After layouting this :
image


image

I get this

image

**Comment by oberlehner** [comment]
Furthermore the undo behaviour of "layout nested subapps" feels strange. pressing undo does not undo the whole layout, it just "undoes" one connection. this means i have to press multiple times undo until i can undo the layout.

**Comment by azoitl** [comment]
@oberlehner is the sub-app size locked?

**Comment by oberlehner** [comment]
> @oberlehner is the sub-app size locked?

no

**Comment by oberlehner** [comment]
Functionilayt is given, UNDO needs to be fixed in a follow up commit

**Pull request merged**
