### PR TITLE
Monitoring rework

### PR DESCRIPTION
**Pull request by mx990**

### CODE REVIEW

**Comment by oberlehner** [comment]
i got this exception:

1) run configurations -> deploy 2) toggle watch on random pins ; then a dialog came that asked me to switch to the monitoring session. 

!ENTRY org.eclipse.core.jobs 4 0 2024-11-07 08:28:35.021
!MESSAGE Connect to Demo
!SUBENTRY 1 org.eclipse.core.jobs 4 2 2024-11-07 08:28:35.022
!MESSAGE An internal error occurred during: "Connect to FORTE_PC".
!STACK 0
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:233)
	at org.eclipse.fordiac.ide.deployment.debug.watch.DeploymentDebugWatchUtils.getResource(DeploymentDebugWatchUtils.java:29)
	at org.eclipse.fordiac.ide.deployment.debug.watch.DeploymentDebugWatchUtils.getResource(DeploymentDebugWatchUtils.java:30)
	at org.eclipse.fordiac.ide.deployment.debug.watch.AbstractVariableWatch.<init>(AbstractVariableWatch.java:35)
	at org.eclipse.fordiac.ide.deployment.debug.watch.AbstractRuntimeWatch.<init>(AbstractRuntimeWatch.java:34)
	at org.eclipse.fordiac.ide.deployment.debug.watch.VarDeclarationWatch.<init>(VarDeclarationWatch.java:38)
	at org.eclipse.fordiac.ide.deployment.debug.watch.IWatch.watchFor(IWatch.java:111)
	at org.eclipse.fordiac.ide.deployment.debug.watch.FBNetworkElementValue.createSubWatch(FBNetworkElementValue.java:65)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at org.eclipse.fordiac.ide.deployment.debug.watch.FBNetworkElementValue.<init>(FBNetworkElementValue.java:43)
	at org.eclipse.fordiac.ide.deployment.debug.watch.FBNetworkElementWatch.<init>(FBNetworkElementWatch.java:27)
	at org.eclipse.fordiac.ide.deployment.debug.watch.IWatch.watchFor(IWatch.java:114)
	at org.eclipse.fordiac.ide.deployment.debug.DeploymentDebugDevice.lambda$11(DeploymentDebugDevice.java:241)
	at java.base/java.util.concurrent.ConcurrentSkipListMap.computeIfAbsent(ConcurrentSkipListMap.java:1462)
	at org.eclipse.fordiac.ide.deployment.debug.DeploymentDebugDevice.addWatch(DeploymentDebugDevice.java:240)
	at org.eclipse.fordiac.ide.deployment.debug.DeploymentDebugDevice.breakpointAdded(DeploymentDebugDevice.java:210)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
	at java.base/java.util.stream.ReferencePipeline$Head.forEachOrdered(ReferencePipeline.java:772)
	at org.eclipse.fordiac.ide.deployment.debug.DeploymentDebugDevice.connect(DeploymentDebugDevice.java:116)
	at org.eclipse.fordiac.ide.deployment.debug.DeploymentDebugTarget.doConnect(DeploymentDebugTarget.java:124)
	at org.eclipse.fordiac.ide.deployment.debug.DeploymentDebugTarget.lambda$2(DeploymentDebugTarget.java:100)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)


after closing and reopen the system, monitoring works fine.

**Comment by oberlehner** [comment]
image
shouldnt i see DO2 and DO3 here in the variables view ?
I am in the debug view

I am not sure if use it in a correct way. But monitoring seems to work, since trigger event updates the output values correct.

**Comment by oberlehner** [comment]
When i right click toggle watch on a block, i don't see any monitoring labels. Only when i right click on a pin.
I would expect, when clicking on a block that i get all pins monitored.
But i don't know if this should be the intended behaviour.

**Comment by mx990** [comment]
> image shouldnt i see DO2 and DO3 here in the variables view ? I am in the debug view
> 
> I am not sure if use it in a correct way. But monitoring seems to work, since trigger event updates the output values correct.

Could it be that you don't have the *Watches* selected in the *Debug* view? It should normally show at least the column headers (*Name* and *Value*), as long as the *Watches* are selected, even if there are no watches.

**Comment by oberlehner** [comment]
> > image shouldnt i see DO2 and DO3 here in the variables view ? I am in the debug view
> > I am not sure if use it in a correct way. But monitoring seems to work, since trigger event updates the output values correct.
> 
> Could it be that you don't have the _Watches_ selected in the _Debug_ view? It should normally show at least the column headers (_Name_ and _Value_), as long as the _Watches_ are selected, even if there are no watches.

ok now i have it.
it was not selected here
image

**Comment by mx990** [comment]
> When i right click toggle watch on a block, i don't see any monitoring labels. Only when i right click on a pin. I would expect, when clicking on a block that i get all pins monitored. But i don't know if this should be the intended behaviour.

Yes, you should have watches for all pins when adding a watchpoint on a block. I believe this may be caused by the exception above. I am still not sure why at least one of the other pins does not seem to have a resource, since it is clearly mapped in the editor.

In the meantime, I have made some changes to gracefully handle watched elements that are not in a resource.

**Review by oberlehner — APPROVED** [review]

**Review by MandKastner — APPROVED** [review]

**Review by azoitl — APPROVED** [review]

**Pull request merged**
