### PR TITLE
Add new FBType "STEPPER" for setpoint stepper

### PR DESCRIPTION
**Pull request by franz-hoepfinger-4diac**
Add new FBType "STEPPER" for setpoint stepper with events and algorithms. Setpoint can be increased or decreased by different values, with maximum and minimum limits. Includes event to load preset value into output.

### CODE REVIEW

**Comment by diplfranzhoepfinger** [comment]
eclipse-4diac/4diac-forte#240

**Review by azoitl — CHANGES_REQUESTED** [review]
Please rework the commit message. A commit message should consist of a one line short summary followed by an empty line with then if necessary a longer description.

**Comment by franz-hoepfinger-4diac** [comment]
> Please rework the commit message. A commit message should consist of a one line short summary followed by an empty line with then if necessary a longer description.

DONE ! 

yes, will pay more attention to this in Future.

**Comment by franz-hoepfinger-4diac** [comment]
cancel this, and make a new PR here: 
https://github.com/eclipse-4diac/4diac-ide/pull/585

**Pull request closed without merging**
