### PR TITLE
removed service sequences for 5 fbt files in utils

### PR DESCRIPTION
**Pull request by MoritzO02**
removed in CSV_Writer_10, CSV_Writer_9, GET_STRUCT_VALUE, GetInstancePath and SET_STRUCT_VALUE
for issue #230

### CODE REVIEW

**Review by azoitl — CHANGES_REQUESTED** [review]
The service squences for CSV_WRITER_9,   CSV_WRITER_10, and GetInstancePath have been specifically adapted for them. Please do not delete them.

**Comment by MoritzO02** [comment]
@azoitl 
There are also some more FBs with service sequences in the subdirectories of the io directory. And around 40 in other directories.
Should i create pull requests for those too?

**Review by azoitl — APPROVED** [review]

**Comment by azoitl** [comment]
> @azoitl There are also some more FBs with service sequences in the subdirectories of the io directory. And around 40 in other directories. Should i create pull requests for those too?

If you have time and don't mind that I will not accept all changes it would be great to have a cleaner typelib. However I don't see it as high prio topic.

**Comment by diplfranzhoepfinger** [comment]
OK, thanks a lot ! @MoritzO02 thanks for the commits.

**Pull request merged**
