### PR TITLE
Merge dialog needs to be run in display thread  #489

### PR DESCRIPTION
**Pull request by azoitl**
As exporting is running in a separate thread all ui interactions triggered by the exporter need to be run in the display thread. This patch fixes that for the merge question dialog.

Furthermore the invocation was cleaned a bit.

https://github.com/eclipse-4diac/4diac-ide/issues/489

### CODE REVIEW

**Review by ernstblechaPT — CHANGES_REQUESTED** [review]
This still fails with a "ThreadAccessException" when opening the CompareEditor (approximatly line 200) - with the following change this seems to be solved:

```
					Display.getDefault().syncExec(() -> {
						opener.openCompareEditor();
					});
```

**Comment by azoitl** [comment]
> This still fails with a "ThreadAccessException" when opening the CompareEditor (approximatly line 200) - with the following change this seems to be solved:
> 
> ```
> 					Display.getDefault().syncExec(() -> {
> 						opener.openCompareEditor();
> 					});
> ```

thanks for noting. I think here an async call is fine. A few lines below I found a further MessageDialog that I had to wrap in an display thread call. Hope this is now all.

**Review by ernstblechaPT — APPROVED** [review]
Yes, syncExec should be fine here - this will only change when the compareEditor opens;

Regarding that other piece of code: This should be mostly dead code as the "no changes" case is handled outside due to my earlier fix from #397

**Comment by azoitl** [comment]
> Yes, syncExec should be fine here - this will only change when the compareEditor opens;
> 
> Regarding that other piece of code: This should be mostly dead code as the "no changes" case is handled outside due to my earlier fix from #397

should we then remove that part. The idea was that when the user selected merge to inform them one nothing was to merge. So it should not be dead code, or?

**Comment by ernstblechaPT** [comment]
> should we then remove that part. The idea was that when the user selected merge to inform them one nothing was to merge. So it should not be dead code, or?

Yes, this is now dead code - the user no longer has the option to select "merge" when there were no changes

**Review by ernstblechaPT — APPROVED** [review]

**Pull request merged**
