### PR TITLE
removed the service sequences from five io files

### PR DESCRIPTION
**Pull request by MoritzO02**
removed for QB, QD, QL, QW, QX
for issue #230

### CODE REVIEW

**Comment by MoritzO02** [comment]
There are also some more FBs with service sequences in the subdirectories of the io directory. And around 40 in other directories.
Should i create pull requests for those too?

**Review by azoitl — APPROVED** [review]

**Comment by franz-hoepfinger-4diac** [comment]
> There are also some more FBs with service sequences in the subdirectories of the io directory. And around 40 in other directories. Should i create pull requests for those too?

@azoitl here was a Question from @MoritzO02  ? 

Thanks, 
Franz

**Comment by azoitl** [comment]
@franz-hoepfinger-4diac: The same question was asked at PR #236. I hope answering once is sufficient.

**Comment by diplfranzhoepfinger** [comment]
> @franz-hoepfinger-4diac: The same question was asked at PR #236. I hope answering once is sufficient.

of course. @MoritzO02 is quite eager in committing, i need to speed up to follow.

**Pull request merged**
