### PR TITLE
Add functions F_NOW and F_NOW_MONOTONIC for time retrieval

### PR DESCRIPTION
**Pull request by franz-hoepfinger-4diac**
Two new functions, F_NOW and F_NOW_MONOTONIC, have been added to retrieve the current time and a clear monotonic time respectively. These functions are wrappers around ST Functions NOW and NOW_MONOTONIC.

### CODE REVIEW

**Comment by franz-hoepfinger-4diac** [comment]
initial Idea: @azoitl

**Review by MartinMelikMerkumians — APPROVED** [review]

**Review by azoitl — CHANGES_REQUESTED** [review]
Please do not add other peoples commits to your PRs. This makes our lives extra hard and is also legally questionable!

**Comment by diplfranzhoepfinger** [comment]
> Please do not add other peoples commits to your PRs. This makes our lives extra hard and is also legally questionable!

That was only the Move of Files and Folder. To have no Merge conflicts later. no single line of code change in this commit.

**Comment by franz-hoepfinger-4diac** [comment]
@azoitl done !

**Review by azoitl — APPROVED** [review]

**Pull request merged**
