### PR TITLE
STOPWATCH: Add new events ET and RESET, update ECState positions, and implement reset functionality. Improve algorithm readability.

### PR DESCRIPTION
**Pull request by franz-hoepfinger-4diac**
the STOPWATCH is not really a Stopwatch. 

Time output is only possible at Stop, think on a Sports Event: you want to get like Round Times, 
also there is no Reset to 0.

### CODE REVIEW

**Comment by azoitl** [comment]
Is it really a good idea to have only one output event and send always EO on all the new different input events?

**Comment by franz-hoepfinger-4diac** [comment]
> Is it really a good idea to have only one output event and send always EO on all the new different input events?

no, that is a BAD idea. 

i will improve !

**Comment by franz-hoepfinger-4diac** [comment]
@azoitl now, this looks nicer right ?

**Review by azoitl — COMMENTED** [review]
I don't know for me are this a bit to much output events now. Especially they are now confusing my how to normally and correctly use that block. The original functionality was to measure the time between a start and a stop event. I understand the ET event and having for that an ETo event. Also the reset event makes sense with a dedicated RESETO but why a STARTO?

**Comment by franz-hoepfinger-4diac** [comment]
so @azoitl we make a EO, which is triggered on START and on RESET ? 

so make 
ETO, RESETO, and EO, 
OK ?

**Comment by azoitl** [comment]
> so @azoitl we make a EO, which is triggered on START and on RESET ?
> 
> so make ETO, RESETO, and EO, OK ?

why an output event on START?

**Comment by franz-hoepfinger-4diac** [comment]
> why an output event on START?

i did remove it: 

image
image

**Review by azoitl — APPROVED** [review]

**Pull request merged**
