### PR TITLE
Add new event-driven bistable FBType E_T_FF_SR.

### PR DESCRIPTION
**Pull request by franz-hoepfinger-4diac**
E_T_FF_SR is a Mix between E_SR and E_T_FF

sometimes a E_T_FF lacks a Reset. 
so in some Application you want a T_FF, but need a definitive OFF Input. 

this Block fullfills this.

### CODE REVIEW

**Comment by franz-hoepfinger-4diac** [comment]
Structure similar to:
https://eclipse.dev/4diac/en_help.php?helppage=html/4diacIDE/use4diacLocally.html

**Review by azoitl — COMMENTED** [review]
Wouldn't an implementation as Basic FB be cleaner?

**Comment by diplfranzhoepfinger** [comment]
> Wouldn't an implementation as Basic FB be cleaner?

I agree, yes. 

would be cleaner ! 

in the Documentation we can still say this is same as the Tutorial, for interested people a nice mind-task. 

for non-interested people it must just work, so does not matter.

**Comment by azoitl** [comment]
> > Wouldn't an implementation as Basic FB be cleaner?
> 
> I agree, yes. 
> 
> would be cleaner ! 
> 
> in the Documentation we can still say this is same as the Tutorial, for interested people a nice mind-task. 
> 
> for non-interested people it must just work, so does not matter.

so?

**Comment by franz-hoepfinger-4diac** [comment]
> > I agree, yes.

> so?

i will design and make a Block.

**Comment by azoitl** [comment]
Great!

**Comment by franz-hoepfinger-4diac** [comment]
see now ...

**Review by azoitl — APPROVED** [review]

**Pull request merged**
