### PR TITLE
changed VersionInfo for Assembling and Splitting Utils

### PR DESCRIPTION
**Pull request by MoritzO02**
changed the VersionInfo for assembling and splitting functions under utils

for issue https://github.com/eclipse-4diac/4diac-ide/pull/221

### CODE REVIEW

**Review by franz-hoepfinger-4diac — APPROVED** [review]
yes, now much clearer, will become also clearer in the Generated Source.

**Review by azoitl — CHANGES_REQUESTED** [review]
Could you please rework the commit message. The current message is describing what I can see in the diff. Please just write what and why you did it.

For Example: reworked version info of the assembling and splitting functionblocks to better document the change history for users.

**Review by diplfranzhoepfinger — APPROVED** [review]

**Comment by azoitl** [comment]
@MoritzO02 I don't see any improvement in commit message. Did I miss anything.

**Comment by franz-hoepfinger-4diac** [comment]
> @MoritzO02 I don't see any improvement in commit message. Did I miss anything.

Agree. @MoritzO02 should change.

**Comment by franz-hoepfinger-4diac** [comment]
> > @MoritzO02 I don't see any improvement in commit message. Did I miss anything.
> 
> Agree. @MoritzO02 should change. He is in Holiday till 12. October.

**Comment by diplfranzhoepfinger** [comment]
@azoitl it is nice now i think.

**Review by azoitl — APPROVED** [review]
Thx for the cleanup!

**Pull request merged**
