### PR TITLE
Remove Comment Value Escaping

### PR DESCRIPTION
**Pull request by azoitl**
Our XML writer is correctly escaping attribute values. If we are also escaping them we get double escaped attribute values which are then wrong.

### CODE REVIEW

**Comment by mx990** [comment]
Should we also write the `Description` attribute in `CommonElementExporter.addIdentification(LibraryElement)` using the normal `XMLStreamWriter.writeAttribute(...)` and then get rid of both `CommonElementExporter.fullyEscapeValue(...)` and `writeAttributeRaw(...)` entirely or is there a reason to do this differently there?

https://github.com/eclipse-4diac/4diac-ide/blob/b49ba72a02d15ad67c4f97d0053d34888702d38c/plugins/org.eclipse.fordiac.ide.model/src/org/eclipse/fordiac/ide/model/dataexport/CommonElementExporter.java#L329-L331

**Comment by azoitl** [comment]
> Should we also write the `Description` attribute in `CommonElementExporter.addIdentification(LibraryElement)` using the normal `XMLStreamWriter.writeAttribute(...)` and then get rid of both `CommonElementExporter.fullyEscapeValue(...)` and `writeAttributeRaw(...)` entirely or is there a reason to do this differently there?
> 
> https://github.com/eclipse-4diac/4diac-ide/blob/b49ba72a02d15ad67c4f97d0053d34888702d38c/plugins/org.eclipse.fordiac.ide.model/src/org/eclipse/fordiac/ide/model/dataexport/CommonElementExporter.java#L329-L331

Thx for pointing this out. This brought me to the root cause of the underlying problem. `fullyEscapeValue(..)'  was originally developed for a different use case and is misused here. The main reason the raw method was used is to better handle newlines in attribute values. But this can be handled much better. Changed that now.

**Comment by mx990** [comment]
I have tried this most recent change and it will now double escape `\n` to `&amp;#10;`, which will be read in again as `&#10;` instead of `\n`.

**Comment by azoitl** [comment]
> I have tried this most recent change and it will now double escape `\n` to `&amp;#10;`, which will be read in again as `&#10;` instead of `\n`.

ah damn, ok now I know why we had the raw thing.

**Review by mx990 — APPROVED** [review]

**Pull request merged**
