### PR TITLE
make multiplexer configurable

### PR DESCRIPTION
**Pull request by bwiesmayr**
Multiplexers are now configurable. This means that pins can be hidden. Import from XML does not yet work, but edits within the IDE are possible.

### CODE REVIEW

**Comment by azoitl** [comment]
With your change pins would be completely gone. I'm not sure if this is what we would like to have for struct muxers. Maybe I would like to provide constants to some struct values and hide that from the ui. This would not be possible with your change or?

**Comment by diplfranzhoepfinger** [comment]
crazy. I might be interested in this, but cannot imagine how it looks.

**Review by azoitl — APPROVED** [review]

**Comment by diplfranzhoepfinger** [comment]
will be in the Next nightly ?

**Comment by azoitl** [comment]
As always when it is merged into develop it will be in the next nightly build.

**Comment by diplfranzhoepfinger** [comment]
4diac IDE

Version: 3.0.0

Build id: 2024-08-27\_0544

testing: 

Backward compatibility is not given. 

other than that it works great.

**Comment by bwiesmayr** [comment]
> 4diac IDE
> 
> Version: 3.0.0
> 
> Build id: 2024-08-27_0544
> 
> testing:
> 
> Backward compatibility is not given. 
> 
> other than that it works great.

May I ask what exactly was not backwards compatible?

**Comment by diplfranzhoepfinger** [comment]
a SUB with a Multiplexer which was configured shows up red. 

then you need to select another Struct, and switch back to the original struct, then the red is gone. 

i guess the XML Read-in is not converting it to the new Format.

**Comment by bwiesmayr** [comment]
Hm, I did not change the format how to store the reference to a structured type itself, so I am a bit surprised. Thanks for reporting

**Pull request merged**
